"""device_token_redesign

Revision ID: e75dd844007b
Revises: fd140481731f
Create Date: 2026-06-15 10:47:22.112240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75dd844007b'
down_revision = 'fd140481731f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    
    # 1. Detect and resolve duplicates safely (keep most recently registered, delete older ones)
    duplicates = connection.execute(sa.text(
        "SELECT fcm_token FROM device_tokens GROUP BY fcm_token HAVING COUNT(*) > 1"
    )).fetchall()
    
    for row in duplicates:
        token = row[0]
        # Find the ID of the most recently created record for this token:
        newest_id = connection.execute(sa.text(
            "SELECT id FROM device_tokens WHERE fcm_token = :token ORDER BY created_at DESC, id DESC LIMIT 1"
        ), {"token": token}).scalar()
        
        # Delete all other rows for this token
        connection.execute(sa.text(
            "DELETE FROM device_tokens WHERE fcm_token = :token AND id != :newest_id"
        ), {"token": token, "newest_id": newest_id})

    # 2. Add columns and unique constraint safely
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=255), server_default='legacy_migration_id', nullable=False))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_unique_constraint('uq_device_tokens_fcm_token', ['fcm_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uq_device_tokens_fcm_token', type_='unique')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
