"""Add website to contacts

Revision ID: fd140481731f
Revises: 3df363fb9ea1
Create Date: 2026-06-14 12:41:49.444430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd140481731f'
down_revision = '3df363fb9ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'website')
    # ### end Alembic commands ###
